### ISSUE TITLE
Feedback for DateTimeInput

### ISSUE THREAD

**Issue by keving119** [Ciphix/ciphixDateTimeInput#1]
Hi,

Thanks for publishing the DateTimeInput widget. We were actually just looking for one (react-based), so that is great!
Upon testing, I noticed a few things (I only tested the Date and Time input type):

1) The widget does not follow date-time localization settings. In the date time widget that we currently use, the format is according to our language settings (dd/MM/yyyy HH:mm), but the ciphix widget has its own date time format.
![image](https://github.com/user-attachments/assets/c20025a4-ea7a-4827-bd10-31be30c0082f)
2) Related, but I would like to set my time in a 24h format
3) Might be a personal preference, but I think it is more user-friendly if you can click anywhere in the widget to open the pop-up instead of only when clicking on the icon. In another widget that we are using, it opens also when clicking on the text, but closes whenever you edit the text, to prevent a mismatch between text and pop-up
4) It would make more sense if the Today button is called Now when you have selected the Date and Time input type
5) I would prefer the pop-up to be closed after clicking the Today button

Thanks in advance!

**Comment by JelleDekker** [comment]
Thanks for your input, but this is all out-of-scope for this widget. The widget simply creates a HTML5 date and/or time element, and from that point everything is controlled by the browser, this is also mentioned under features

> Formatting and calendar/time pickers are controlled by browser

So the formatting you is simply the formatting you have set your browser to (or the interpretation your browser takes from your system settings). And also the behavior, triggers and location of the date/time pickers are completely browser based. If you compare the page in Chrome and Firefox you'll already see a difference in date/time pickers for instance.

The upside of working with HTML5 elements is that it's lightweight and all desktop and mobile browsers support it. The downside is that the HTML standard offers no customization and leaves all decisions on format etc with the browser.
